"""add matchups and venue tabless

Revision ID: 073a680f79fb
Revises: 752697f7f15c
Create Date: 2026-06-25 23:45:26.951066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073a680f79fb'
down_revision: Union[str, Sequence[str], None] = '752697f7f15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchups_pvp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.UUID(), nullable=False),
    sa.Column('bowler_id', sa.UUID(), nullable=False),
    sa.Column('runs_scored', sa.Integer(), nullable=True),
    sa.Column('balls_faced', sa.Integer(), nullable=True),
    sa.Column('dismissals', sa.Integer(), nullable=True),
    sa.Column('dots_faced', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batter_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchups_pvp_batter_id'), 'matchups_pvp', ['batter_id'], unique=False)
    op.create_index(op.f('ix_matchups_pvp_bowler_id'), 'matchups_pvp', ['bowler_id'], unique=False)
    op.create_index(op.f('ix_matchups_pvp_id'), 'matchups_pvp', ['id'], unique=False)
    op.create_table('venue_mastery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('venue_normalized', sa.String(), nullable=False),
    sa.Column('bat_runs', sa.Integer(), nullable=True),
    sa.Column('bat_balls', sa.Integer(), nullable=True),
    sa.Column('bat_dismissals', sa.Integer(), nullable=True),
    sa.Column('bowl_balls', sa.Integer(), nullable=True),
    sa.Column('bowl_runs_conceded', sa.Integer(), nullable=True),
    sa.Column('bowl_wickets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_mastery_id'), 'venue_mastery', ['id'], unique=False)
    op.create_index(op.f('ix_venue_mastery_player_id'), 'venue_mastery', ['player_id'], unique=False)
    op.create_index(op.f('ix_venue_mastery_venue_normalized'), 'venue_mastery', ['venue_normalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venue_mastery_venue_normalized'), table_name='venue_mastery')
    op.drop_index(op.f('ix_venue_mastery_player_id'), table_name='venue_mastery')
    op.drop_index(op.f('ix_venue_mastery_id'), table_name='venue_mastery')
    op.drop_table('venue_mastery')
    op.drop_index(op.f('ix_matchups_pvp_id'), table_name='matchups_pvp')
    op.drop_index(op.f('ix_matchups_pvp_bowler_id'), table_name='matchups_pvp')
    op.drop_index(op.f('ix_matchups_pvp_batter_id'), table_name='matchups_pvp')
    op.drop_table('matchups_pvp')
    # ### end Alembic commands ###
