"""add multiplayer mock auction tables safely

Revision ID: 368f2c182093
Revises: 073a680f79fb
Create Date: 2026-07-03 20:56:48.053099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368f2c182093'
down_revision: Union[str, Sequence[str], None] = '073a680f79fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create auction_lobbies WITHOUT the highest_bidder_id Foreign Key inside it
    op.create_table('auction_lobbies',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('room_code', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('venue_selected', sa.String(), nullable=True),
        sa.Column('format_selected', sa.String(), nullable=True),
        sa.Column('current_player_id', sa.UUID(), nullable=True),
        sa.Column('current_bid', sa.Integer(), nullable=True),
        sa.Column('highest_bidder_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['current_player_id'], ['players.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_lobbies_id'), 'auction_lobbies', ['id'], unique=False)
    op.create_index(op.f('ix_auction_lobbies_room_code'), 'auction_lobbies', ['room_code'], unique=True)

    # 2. Create participants next (now that auction_lobbies exists)
    op.create_table('participants',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('lobby_id', sa.UUID(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('purse_remaining', sa.Integer(), nullable=True),
        sa.Column('squad_size', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['lobby_id'], ['auction_lobbies.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_index(op.f('ix_participants_lobby_id'), 'participants', ['lobby_id'], unique=False)

    # 3. Create draft_picks
    op.create_table('draft_picks',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('lobby_id', sa.UUID(), nullable=False),
        sa.Column('participant_id', sa.UUID(), nullable=False),
        sa.Column('player_id', sa.UUID(), nullable=False),
        sa.Column('sold_price', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['lobby_id'], ['auction_lobbies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_picks_id'), 'draft_picks', ['id'], unique=False)
    op.create_index(op.f('ix_draft_picks_lobby_id'), 'draft_picks', ['lobby_id'], unique=False)
    op.create_index(op.f('ix_draft_picks_participant_id'), 'draft_picks', ['participant_id'], unique=False)

    # 4. Now that BOTH tables physically exist, safely apply the missing circular FK constraint!
    op.create_foreign_key(
        'fk_auction_lobbies_highest_bidder',
        'auction_lobbies', 'participants',
        ['highest_bidder_id'], ['id'],
        ondelete='SET NULL'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'base_price')
    op.drop_index(op.f('ix_draft_picks_participant_id'), table_name='draft_picks')
    op.drop_index(op.f('ix_draft_picks_lobby_id'), table_name='draft_picks')
    op.drop_index(op.f('ix_draft_picks_id'), table_name='draft_picks')
    op.drop_table('draft_picks')
    op.drop_index(op.f('ix_participants_lobby_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_auction_lobbies_room_code'), table_name='auction_lobbies')
    op.drop_index(op.f('ix_auction_lobbies_id'), table_name='auction_lobbies')
    op.drop_table('auction_lobbies')
    # ### end Alembic commands ###
